### ISSUE TITLE
 what the different  with LC_Symtab  and  LC_DYSYMTAB   ?

### ISSUE THREAD

**Issue by vedon** [DeVaukz/MachO-Kit#1]

**Comment by DeVaukz** [comment]
LC_SYMTAB only provides the locations of the symbol and string tables.  LC_DYSYMTAB provides much more information including where to find the rebasing information plus the ranges of local, external, and undefined symbols within the symbol table, and much more.  Checkout the comments for `struct dysymtab_command` in <mach-o/loader.h>

**Comment by vedon** [comment]
@DeVaukz  Thank you !  Is the LC_DYSYMTAB contain the LC_SYMTAB？ LC_SYMTAB is the subset of the LC_DYSYMTAB?

**Comment by DeVaukz** [comment]
No.  They are separate but LC_SYMTAB must be present if LC_DYSYMTAB is present.

**Comment by vedon** [comment]
@DeVaukz  ok ,I get that .If i have one symbol ,could you have any idea to confirm the range of the symbol in assembly ? Just like the pic show?

![b91c654d-288a-4e19-a3b6-1864ea28f811](https://cloud.githubusercontent.com/assets/1811570/8904976/7d0dfeba-3496-11e5-8b89-9bea65050992.png)

**Comment by DeVaukz** [comment]
Symbols relate a name to a _specific_ address, not a range.  You would need to parse the assembly code beginning at the address associated with the target function's symbol, stopping when you encounter another prolog (which signifies the beginning of a new function) in order to find the end of your target function.

**Comment by vedon** [comment]
@DeVaukz  thx ! I know how to deal with this
